nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.4.0.cjs

packageExtensions:
  '@commitlint/load@19.4.0':
    dependencies:
      '@types/node': '*'
      'typescript': '*'
  'nativewind@2.0.11':
    dependencies:
      'react': '*'
  'react-native@0.74.5':
    dependencies:
      '@babel/preset-env': '^7.1.6'
  '@react-native/eslint-config@0.75.1':
    dependencies:
      'typescript': '*'
  '@typescript-eslint/type-utils@8.1.0':
    dependencies:
      'eslint': '^8.57.0'
  '@typescript-eslint/utils@*':
    dependencies:
      'typescript': '*'
  '@react-native/babel-plugin-codegen@*':
    dependencies:
      '@babel/preset-env': '^7.1.6'
  'babel-plugin-transform-flow-enums@0.0.2':
    dependencies:
      '@babel/core': '^7.0.0-0'
  '@react-native/babel-plugin-codegen@0.75.1':
    dependencies:
      '@babel/core': '^7.0.0'
  'react-native@0.75.1':
    dependencies:
      '@babel/preset-env': '^7.1.6'
      '@babel/core': '^7.0.0'
